<?php

namespace JASoft\Hrm\PayrollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdentityDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentityDocumentTypeRepository extends EntityRepository
{
}
