<?php

namespace JASoft\ViringoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemUserRepository extends EntityRepository
    implements \Symfony\Component\Security\Core\User\UserProviderInterface
{

    public function loadUserByUsername($username) {
        
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user) {
        
    }

    public function supportsClass($class) {
        
    }
}
